# Generated by Django 5.0.7 on 2024-08-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtihon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
