# Generated by Django 5.0.7 on 2024-08-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtihon_app', '0002_photos_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
